// DO NOT EDIT.
// Generated by asks-ts codegen.

import type { ContextBridge, RpcEnvelopeBridge, Workload } from '@actor-rtc/actr';

import { PROMPT_ROUTE_KEY, ATTACH_ROUTE_KEY } from './generated/ask.client.js';
import { Ask_AssistantReply, Ask_AttachRequest, Ask_AttachResponse, Ask_UsrPromptRequest } from './generated/ask.pb.js';

export interface AskServiceHandlers {
  prompt: (request: Ask_UsrPromptRequest, ctx: ContextBridge) => Promise<Ask_AssistantReply>;
  attach: (request: Ask_AttachRequest, ctx: ContextBridge) => Promise<Ask_AttachResponse>;
}

export class AskServiceWorkload implements Workload {
  constructor(private readonly handlers: AskServiceHandlers) {}

  async onStart(_ctx: ContextBridge): Promise<void> {
    console.log('AskService workload started');
  }

  async onStop(_ctx: ContextBridge): Promise<void> {
    console.log('AskService workload stopped');
  }

  async dispatch(ctx: ContextBridge, envelope: RpcEnvelopeBridge): Promise<Buffer> {
    if (envelope.routeKey === PROMPT_ROUTE_KEY) {
      const request = Ask_UsrPromptRequest.decode(envelope.payload);
      const response = await this.handlers.prompt(request, ctx);
      return Ask_AssistantReply.encode(response);
    }

    if (envelope.routeKey === ATTACH_ROUTE_KEY) {
      const request = Ask_AttachRequest.decode(envelope.payload);
      const response = await this.handlers.attach(request, ctx);
      return Ask_AttachResponse.encode(response);
    }

    throw new Error(`Unknown route: ${envelope.routeKey}`);
  }
}

export function createAskServiceWorkload(handlers: AskServiceHandlers): AskServiceWorkload {
  return new AskServiceWorkload(handlers);
}