// DO NOT EDIT.
// Generated by asks-ts codegen.

import type { ContextBridge, RpcEnvelopeBridge, Workload } from '@actor-rtc/actr';

import { USRPROMPT_ROUTE_KEY, ATTACH_ROUTE_KEY, UNREGISTERDATASTREAM_ROUTE_KEY } from './generated/ask_service.client.js';
import { AskService_AssistantReply, AskService_AttachRequest, AskService_AttachResponse, AskService_UnregisterRequest, AskService_UnregisterResponse, AskService_UsrPromptRequest } from './generated/ask_service.pb.js';

export interface AskServiceHandlers {
  usrPrompt: (request: AskService_UsrPromptRequest, ctx: ContextBridge) => Promise<AskService_AssistantReply>;
  attach: (request: AskService_AttachRequest, ctx: ContextBridge) => Promise<AskService_AttachResponse>;
  unregisterDataStream: (request: AskService_UnregisterRequest, ctx: ContextBridge) => Promise<AskService_UnregisterResponse>;
}

export class AskServiceWorkload implements Workload {
  constructor(private readonly handlers: AskServiceHandlers) {}

  async onStart(_ctx: ContextBridge): Promise<void> {
    console.log('AskService workload started');
  }

  async onStop(_ctx: ContextBridge): Promise<void> {
    console.log('AskService workload stopped');
  }

  async dispatch(ctx: ContextBridge, envelope: RpcEnvelopeBridge): Promise<Buffer> {
    if (envelope.routeKey === USRPROMPT_ROUTE_KEY) {
      const request = AskService_UsrPromptRequest.decode(envelope.payload);
      const response = await this.handlers.usrPrompt(request, ctx);
      return AskService_AssistantReply.encode(response);
    }

    if (envelope.routeKey === ATTACH_ROUTE_KEY) {
      const request = AskService_AttachRequest.decode(envelope.payload);
      const response = await this.handlers.attach(request, ctx);
      return AskService_AttachResponse.encode(response);
    }

    if (envelope.routeKey === UNREGISTERDATASTREAM_ROUTE_KEY) {
      const request = AskService_UnregisterRequest.decode(envelope.payload);
      const response = await this.handlers.unregisterDataStream(request, ctx);
      return AskService_UnregisterResponse.encode(response);
    }

    throw new Error(`Unknown route: ${envelope.routeKey}`);
  }
}

export function createAskServiceWorkload(handlers: AskServiceHandlers): AskServiceWorkload {
  return new AskServiceWorkload(handlers);
}